language: c++
install:
  - sudo apt-get -qq update
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install libsdl2-2.0-0 libsdl2-dev libsdl2-ttf-2.0-0 libsdl2-ttf-dev
  - sudo apt-get install dh-make
script:
  - make
  - cd .. && mkdir -p markit
  - cp Markit/pkg/deb/debbuild.sh markit
  - cd markit && bash debbuild.sh
